import {
  GoogleSheetTab,
  DriveFolderNode,
  User,
  Account,
  AccountAllocation,
  FollowUp,
  PTPRecord,
  RecoveryRecord,
  FieldVisit,
  PhotoRecord,
  VoiceNoteRecord,
  DocumentRecord,
  ActivityLog,
  NotificationItem,
  CommissionRecord,
  Branch,
  Area,
  Zone,
  CommissionSettings,
} from '../types';

export function compileAll19GoogleSheets(data: {
  users: User[];
  accounts: Account[];
  allocations: AccountAllocation[];
  followups: FollowUp[];
  ptps: PTPRecord[];
  recoveries: RecoveryRecord[];
  visits: FieldVisit[];
  photos: PhotoRecord[];
  documents: DocumentRecord[];
  voiceNotes: VoiceNoteRecord[];
  activityLogs: ActivityLog[];
  notifications: NotificationItem[];
  commissions: CommissionRecord[];
  branches: Branch[];
  areas: Area[];
  zones: Zone[];
  commissionSettings: CommissionSettings;
}): GoogleSheetTab[] {
  const {
    users,
    accounts,
    allocations,
    followups,
    ptps,
    recoveries,
    visits,
    photos,
    documents,
    voiceNotes,
    activityLogs,
    notifications,
    commissions,
    branches,
    areas,
    zones,
    commissionSettings,
  } = data;

  const agents = users.filter((u) => u.role === 'agent');

  return [
    {
      id: 'sheet_1',
      title: 'Users',
      sheetNumber: 1,
      description: 'System credentials, passwords, roles, assignments, status and permissions (all users preserved permanently)',
      columns: ['User ID', 'Username', 'Name', 'Email', 'Password', 'Role', 'Branch', 'Area', 'Zone', 'Agent ID', 'Mobile', 'Joining Date', 'Status', 'Active'],
      rowCount: users.length,
      records: users.map((u) => ({
        'User ID': u.id,
        Username: u.username,
        Name: u.name,
        Email: u.email,
        Password: u.password || (u.role === 'admin' ? 'Admin@2026' : u.role === 'coordinator' ? 'Coord@2026' : 'Agent@2026'),
        Role: u.role.toUpperCase(),
        Branch: u.branch,
        Area: u.area,
        Zone: u.zone,
        'Agent ID': u.agentId || 'N/A',
        Mobile: u.mobile,
        'Joining Date': u.joiningDate,
        Status: u.isDeleted ? 'DELETED' : u.active ? 'ACTIVE' : 'INACTIVE',
        Active: u.isDeleted ? 'NO (Preserved in Sheet)' : u.active ? 'YES' : 'NO',
      })),
    },
    {
      id: 'sheet_2',
      title: 'Agents',
      sheetNumber: 2,
      description: 'Recovery Agent profiles, passwords, targets, assigned zones and active status',
      columns: ['Agent ID', 'Name', 'Mobile', 'Password', 'Branch', 'Area', 'Monthly Target (₹)', 'Joining Date', 'Status'],
      rowCount: agents.length,
      records: agents.map((a) => ({
        'Agent ID': a.agentId || a.id,
        Name: a.name,
        Mobile: a.mobile,
        Password: a.password || 'Agent@2026',
        Branch: a.branch,
        Area: a.area,
        'Monthly Target (₹)': a.monthlyTarget || 300000,
        'Joining Date': a.joiningDate,
        Status: a.isDeleted ? 'DELETED (Preserved)' : a.active ? 'ACTIVE' : 'INACTIVE',
      })),
    },
    {
      id: 'sheet_3',
      title: 'Customers',
      sheetNumber: 3,
      description: 'Customer contact details, addresses, and risk categorization',
      columns: ['Account ID', 'Customer Name', 'Mobile Number', 'Alternate Mobile', 'Address', 'City', 'Customer Category'],
      rowCount: accounts.length,
      records: accounts.map((acc) => ({
        'Account ID': acc.accountId,
        'Customer Name': acc.customerName,
        'Mobile Number': acc.mobile,
        'Alternate Mobile': acc.alternateMobile || 'N/A',
        Address: acc.address,
        City: acc.city,
        'Customer Category': acc.customerCategory,
      })),
    },
    {
      id: 'sheet_4',
      title: 'Accounts',
      sheetNumber: 4,
      description: 'Master loan account records, sanctions, overdue buckets, PTP Count and status',
      columns: [
        'Branch Code',
        'Branch Name',
        'Account ID',
        'Customer Name',
        'Product Description',
        'Facility',
        'Sanction Limit (₹)',
        'Loan Balance (₹)',
        'NPA Date',
        'Contact Number',
        'Customer ID',
        'Address',
        'PTP Count',
        'Category',
        'Account Status',
        'Assigned Agent',
        'PTP Status',
        'Total Recovered (₹)',
      ],
      rowCount: accounts.length,
      records: accounts.map((acc) => ({
        'Branch Code': acc.branchCode || 'BR-01',
        'Branch Name': acc.branch,
        'Account ID': acc.accountId,
        'Customer Name': acc.customerName,
        'Product Description': acc.loanType,
        Facility: acc.facility || 'Term Loan',
        'Sanction Limit (₹)': acc.sanctionAmount,
        'Loan Balance (₹)': acc.outstandingAmount,
        'NPA Date': acc.npaDate || '2024-03-31',
        'Contact Number': acc.mobile,
        'Customer ID': acc.customerCode || acc.id,
        Address: acc.address,
        'PTP Count': acc.ptpCount ?? 0,
        Category: acc.customerCategory,
        'Account Status': acc.accountStatus,
        'Assigned Agent': `${acc.assignedAgentId} (${acc.assignedAgentName})`,
        'PTP Status': acc.ptpStatus || 'None',
        'Total Recovered (₹)': acc.totalRecovered,
      })),
    },
    {
      id: 'sheet_5',
      title: 'Account_Allocation',
      sheetNumber: 5,
      description: 'Active and historic agent allocation mapping with timestamps',
      columns: ['Allocation ID', 'Account ID', 'Agent ID', 'Agent Name', 'Allocated By', 'Allocation Date', 'Branch', 'Area', 'Remarks'],
      rowCount: allocations.length,
      records: allocations.map((al) => ({
        'Allocation ID': al.id,
        'Account ID': al.accountId,
        'Agent ID': al.agentId,
        'Agent Name': al.agentName,
        'Allocated By': al.allocatedBy,
        'Allocation Date': al.allocationDate,
        Branch: al.branch,
        Area: al.area,
        Remarks: al.remarks || 'Standard allocation',
      })),
    },
    {
      id: 'sheet_6',
      title: 'Followups',
      sheetNumber: 6,
      description: 'Telephonic and personal customer contact logs and next action dates',
      columns: ['Followup ID', 'Account ID', 'Customer Name', 'Agent ID', 'Date', 'Time', 'Call Status', 'Customer Response', 'Agent Remarks', 'Next Followup Date', 'Next Followup Time'],
      rowCount: followups.length,
      records: followups.map((f) => ({
        'Followup ID': f.id,
        'Account ID': f.accountId,
        'Customer Name': f.customerName,
        'Agent ID': `${f.agentId} (${f.agentName})`,
        Date: f.date,
        Time: f.time,
        'Call Status': f.status,
        'Customer Response': f.customerResponse,
        'Agent Remarks': f.agentRemarks,
        'Next Followup Date': f.nextFollowUpDate || 'N/A',
        'Next Followup Time': f.nextFollowUpTime || 'N/A',
      })),
    },
    {
      id: 'sheet_7',
      title: 'PTP',
      sheetNumber: 7,
      description: 'Promise to Pay commitments, target dates, modes and resolution statuses',
      columns: ['PTP ID', 'Account ID', 'Customer Name', 'Agent ID', 'PTP Amount (₹)', 'PTP Date', 'Payment Mode', 'Commitment Details', 'Status', 'Created At', 'Resolved Date'],
      rowCount: ptps.length,
      records: ptps.map((p) => ({
        'PTP ID': p.id,
        'Account ID': p.accountId,
        'Customer Name': p.customerName,
        'Agent ID': `${p.agentId} (${p.agentName})`,
        'PTP Amount (₹)': p.amount,
        'PTP Date': p.ptpDate,
        'Payment Mode': p.ptpMode,
        'Commitment Details': p.customerCommitment,
        Status: p.status,
        'Created At': p.createdAt,
        'Resolved Date': p.resolvedDate || 'Pending',
      })),
    },
    {
      id: 'sheet_8',
      title: 'Recovery',
      sheetNumber: 8,
      description: 'Collected payments, payment modes, receipts and 10% agent commission',
      columns: ['Recovery ID', 'Account ID', 'Customer Name', 'Agent ID', 'Recovered Amount (₹)', 'Recovery Date', 'Ref Number', 'Mode', 'Receipt Number', '10% Commission (₹)', 'Commission Status', 'Drive Proof File ID'],
      rowCount: recoveries.length,
      records: recoveries.map((r) => ({
        'Recovery ID': r.recoveryId || r.id,
        'Account ID': r.accountId,
        'Customer Name': r.customerName,
        'Agent ID': `${r.agentId} (${r.agentName})`,
        'Recovered Amount (₹)': r.amount,
        'Recovery Date': r.recoveryDate,
        'Ref Number': r.referenceNumber,
        Mode: r.paymentMode,
        'Receipt Number': r.receiptNumber,
        '10% Commission (₹)': r.commissionAmount,
        'Commission Status': r.commissionPaidStatus,
        'Drive Proof File ID': r.proofDriveFileId || 'N/A',
      })),
    },
    {
      id: 'sheet_9',
      title: 'Visits',
      sheetNumber: 9,
      description: 'On-ground field visit audit logs with GPS latitude, longitude and timings',
      columns: ['Visit ID', 'Account ID', 'Customer Name', 'Agent ID', 'Date', 'Start Time', 'End Time', 'Latitude', 'Longitude', 'Accuracy (m)', 'Visit Status', 'Visit Remarks', 'Photos Count', 'Voice Notes Count'],
      rowCount: visits.length,
      records: visits.map((v) => ({
        'Visit ID': v.visitId || v.id,
        'Account ID': v.accountId,
        'Customer Name': v.customerName,
        'Agent ID': `${v.agentId} (${v.agentName})`,
        Date: v.date,
        'Start Time': v.startTime,
        'End Time': v.endTime || 'N/A',
        Latitude: v.latitude,
        Longitude: v.longitude,
        'Accuracy (m)': v.accuracyMeters || 5.0,
        'Visit Status': v.visitStatus,
        'Visit Remarks': v.visitRemarks,
        'Photos Count': v.photoDriveFileIds?.length || 0,
        'Voice Notes Count': v.voiceNoteDriveFileIds?.length || 0,
      })),
    },
    {
      id: 'sheet_10',
      title: 'Photos',
      sheetNumber: 10,
      description: 'Geo-tagged watermarked photographs audit metadata & Google Drive file IDs',
      columns: ['Photo ID', 'Account ID', 'Customer ID', 'Agent ID', 'Date', 'Time', 'Latitude', 'Longitude', 'Visit ID', 'Agent Remark', 'Google Drive File ID', 'Drive Folder Path', 'Upload Status'],
      rowCount: photos.length,
      records: photos.map((ph) => ({
        'Photo ID': ph.photoId || ph.id,
        'Account ID': ph.accountId,
        'Customer ID': ph.customerId,
        'Agent ID': `${ph.agentId} (${ph.agentName})`,
        Date: ph.date,
        Time: ph.time,
        Latitude: ph.latitude,
        Longitude: ph.longitude,
        'Visit ID': ph.visitId || 'N/A',
        'Agent Remark': ph.agentRemark,
        'Google Drive File ID': ph.driveFileId,
        'Drive Folder Path': ph.driveFolder,
        'Upload Status': ph.uploadStatus,
      })),
    },
    {
      id: 'sheet_11',
      title: 'Documents',
      sheetNumber: 11,
      description: 'KYC, panchnama, legal notices, and payment proofs linked to Google Drive',
      columns: ['Document ID', 'Account ID', 'Customer Name', 'Document Type', 'File Name', 'Uploaded By', 'Date Time', 'File Size (KB)', 'Google Drive File ID'],
      rowCount: documents.length,
      records: documents.map((d) => ({
        'Document ID': d.documentId || d.id,
        'Account ID': d.accountId,
        'Customer Name': d.customerName,
        'Document Type': d.documentType,
        'File Name': d.fileName,
        'Uploaded By': d.uploadedByName,
        'Date Time': d.dateTime,
        'File Size (KB)': Math.round(d.fileSizeBytes / 1024),
        'Google Drive File ID': d.driveFileId,
      })),
    },
    {
      id: 'sheet_12',
      title: 'Voice_Notes',
      sheetNumber: 12,
      description: 'Recorded audio field notes, agent statements and Google Drive audio file links',
      columns: ['Voice Note ID', 'Account ID', 'Agent ID', 'Title', 'Date', 'Time', 'Duration (s)', 'Visit ID', 'Transcription / Note', 'Google Drive Audio ID'],
      rowCount: voiceNotes.length,
      records: voiceNotes.map((vn) => ({
        'Voice Note ID': vn.voiceNoteId || vn.id,
        'Account ID': vn.accountId,
        'Agent ID': `${vn.agentId} (${vn.agentName})`,
        Title: vn.title,
        Date: vn.date,
        Time: vn.time,
        'Duration (s)': vn.durationSeconds,
        'Visit ID': vn.visitId || 'N/A',
        'Transcription / Note': vn.transcription || 'Voice audio recording captured.',
        'Google Drive Audio ID': vn.driveFileId,
      })),
    },
    {
      id: 'sheet_13',
      title: 'Activity_Log',
      sheetNumber: 13,
      description: 'Full chronological audit trail of all agent and user operations',
      columns: ['Log ID', 'Timestamp', 'User ID', 'User Name', 'Role', 'Account ID', 'Action Type', 'Action Details'],
      rowCount: activityLogs.length,
      records: activityLogs.map((act) => ({
        'Log ID': act.id,
        Timestamp: act.timestamp,
        'User ID': act.userId,
        'User Name': act.userName,
        Role: act.role.toUpperCase(),
        'Account ID': act.accountId || 'N/A',
        'Action Type': act.actionType,
        'Action Details': act.details,
      })),
    },
    {
      id: 'sheet_14',
      title: 'Notifications',
      sheetNumber: 14,
      description: 'System alerts, WhatsApp triggers, PTP reminders and collection broadcasts',
      columns: ['Notification ID', 'Timestamp', 'Recipient Role', 'Target User ID', 'Type', 'Title', 'Message Content', 'Read Status', 'Linked Account'],
      rowCount: notifications.length,
      records: notifications.map((n) => ({
        'Notification ID': n.id,
        Timestamp: n.timestamp,
        'Recipient Role': n.recipientRole.toUpperCase(),
        'Target User ID': n.recipientUserId || 'ALL',
        Type: n.type,
        Title: n.title,
        'Message Content': n.message,
        'Read Status': n.read ? 'READ' : 'UNREAD',
        'Linked Account': n.accountId || 'N/A',
      })),
    },
    {
      id: 'sheet_15',
      title: 'Commission',
      sheetNumber: 15,
      description: '10% Recovery Agent commission earnings, payout approvals and status',
      columns: ['Commission ID', 'Agent ID', 'Agent Name', 'Recovery ID', 'Account ID', 'Recovery Amount (₹)', 'Rate (%)', 'Commission Earned (₹)', 'Date', 'Payout Status', 'Paid Date'],
      rowCount: commissions.length,
      records: commissions.map((c) => ({
        'Commission ID': c.id,
        'Agent ID': c.agentId,
        'Agent Name': c.agentName,
        'Recovery ID': c.recoveryId,
        'Account ID': c.accountId,
        'Recovery Amount (₹)': c.recoveryAmount,
        'Rate (%)': `${c.commissionRate}%`,
        'Commission Earned (₹)': c.commissionAmount,
        Date: c.date,
        'Payout Status': c.status,
        'Paid Date': c.paidDate || 'N/A',
      })),
    },
    {
      id: 'sheet_16',
      title: 'Branches',
      sheetNumber: 16,
      description: 'Operational bank recovery branch units and managers',
      columns: ['Branch ID', 'Branch Name', 'Branch Code', 'Area', 'Zone', 'Branch Manager'],
      rowCount: branches.length,
      records: branches.map((b) => ({
        'Branch ID': b.id,
        'Branch Name': b.name,
        'Branch Code': b.code,
        Area: b.area,
        Zone: b.zone,
        'Branch Manager': b.managerName,
      })),
    },
    {
      id: 'sheet_17',
      title: 'Areas',
      sheetNumber: 17,
      description: 'Geographical cluster recovery area definitions',
      columns: ['Area ID', 'Area Name', 'Zone'],
      rowCount: areas.length,
      records: areas.map((ar) => ({
        'Area ID': ar.id,
        'Area Name': ar.name,
        Zone: ar.zone,
      })),
    },
    {
      id: 'sheet_18',
      title: 'Zones',
      sheetNumber: 18,
      description: 'State and regional recovery operational zones',
      columns: ['Zone ID', 'Zone Name', 'Zone Head'],
      rowCount: zones.length,
      records: zones.map((z) => ({
        'Zone ID': z.id,
        'Zone Name': z.name,
        'Zone Head': z.headName,
      })),
    },
    {
      id: 'sheet_19',
      title: 'Settings',
      sheetNumber: 19,
      description: 'System configuration parameters, 10% commission rate and drive folders',
      columns: ['Setting Key', 'Setting Value', 'Description', 'Last Updated'],
      rowCount: 6,
      records: [
        { 'Setting Key': 'DEFAULT_COMMISSION_PERCENTAGE', 'Setting Value': `${commissionSettings.defaultRate}%`, Description: 'Default recovery agent commission rate applied to all collections', 'Last Updated': '2026-08-23' },
        { 'Setting Key': 'STORAGE_SYSTEM', 'Setting Value': 'Google Sheets + Google Drive (Prototype Layer)', Description: 'Active storage adapter supporting seamless DB migration', 'Last Updated': '2026-08-23' },
        { 'Setting Key': 'DRIVE_ROOT_FOLDER', 'Setting Value': 'ScaleSupport', Description: 'Root Google Drive folder for accounts, attachments and reports', 'Last Updated': '2026-08-23' },
        { 'Setting Key': 'MINIMUM_PAYOUT_AMOUNT', 'Setting Value': `₹${commissionSettings.minimumPayoutAmount}`, Description: 'Minimum accrued commission required before payout processing', 'Last Updated': '2026-08-23' },
        { 'Setting Key': 'AUTO_APPROVAL_THRESHOLD', 'Setting Value': `₹${commissionSettings.autoApprovalThreshold}`, Description: 'Recoveries up to this amount auto-approve agent commission', 'Last Updated': '2026-08-23' },
        { 'Setting Key': 'WATERMARK_LOGO_TEXT', 'Setting Value': 'ScaleSupport • RECOVERY SYSTEM', Description: 'Official title stamped on all geo-tagged field camera snapshots', 'Last Updated': '2026-08-23' },
      ],
    },
  ];
}

export function generateGoogleDriveHierarchy(accounts: Account[], photos: PhotoRecord[], documents: DocumentRecord[], voiceNotes: VoiceNoteRecord[]): DriveFolderNode {
  return {
    id: 'drv_root',
    name: 'ScaleSupport',
    type: 'folder',
    path: '/ScaleSupport',
    createdAt: '2026-08-01',
    children: [
      {
        id: 'drv_accounts',
        name: 'Accounts',
        type: 'folder',
        path: '/ScaleSupport/Accounts',
        fileCount: accounts.length,
        createdAt: '2026-08-01',
        children: accounts.map((acc) => {
          const accPhotos = photos.filter((p) => p.accountId === acc.accountId);
          const accDocs = documents.filter((d) => d.accountId === acc.accountId);
          const accVoice = voiceNotes.filter((v) => v.accountId === acc.accountId);

          return {
            id: `drv_acc_${acc.accountId}`,
            name: acc.accountId,
            type: 'folder',
            path: `/ScaleSupport/Accounts/${acc.accountId}`,
            fileCount: accPhotos.length + accDocs.length + accVoice.length,
            createdAt: acc.allocationDate,
            children: [
              {
                id: `drv_${acc.accountId}_photos`,
                name: 'Photos',
                type: 'folder',
                path: `/ScaleSupport/Accounts/${acc.accountId}/Photos`,
                fileCount: accPhotos.length,
                createdAt: acc.allocationDate,
                children: accPhotos.map((p) => ({
                  id: p.driveFileId,
                  name: `${p.photoId}_Watermarked_GeoTag.jpg`,
                  type: 'file',
                  path: `/ScaleSupport/Accounts/${acc.accountId}/Photos/${p.photoId}.jpg`,
                  driveFileId: p.driveFileId,
                  size: '420 KB',
                  mimeType: 'image/jpeg',
                  createdAt: p.date,
                  previewUrl: p.dataUrl,
                })),
              },
              {
                id: `drv_${acc.accountId}_docs`,
                name: 'Documents',
                type: 'folder',
                path: `/ScaleSupport/Accounts/${acc.accountId}/Documents`,
                fileCount: accDocs.length,
                createdAt: acc.allocationDate,
                children: accDocs.map((d) => ({
                  id: d.driveFileId,
                  name: d.fileName,
                  type: 'file',
                  path: `/ScaleSupport/Accounts/${acc.accountId}/Documents/${d.fileName}`,
                  driveFileId: d.driveFileId,
                  size: `${Math.round(d.fileSizeBytes / 1024)} KB`,
                  mimeType: 'application/pdf',
                  createdAt: d.dateTime,
                })),
              },
              {
                id: `drv_${acc.accountId}_recovery_proof`,
                name: 'Recovery_Proof',
                type: 'folder',
                path: `/ScaleSupport/Accounts/${acc.accountId}/Recovery_Proof`,
                fileCount: 1,
                createdAt: acc.allocationDate,
                children: [
                  {
                    id: `drv_rec_proof_${acc.accountId}`,
                    name: `Recovery_Slip_${acc.accountId}.pdf`,
                    type: 'file',
                    path: `/ScaleSupport/Accounts/${acc.accountId}/Recovery_Proof/Slip.pdf`,
                    driveFileId: `DRV_REC_${acc.accountId}_PROOF`,
                    size: '180 KB',
                    mimeType: 'application/pdf',
                    createdAt: '2026-08-23',
                  },
                ],
              },
              {
                id: `drv_${acc.accountId}_visit_proof`,
                name: 'Visit_Proof',
                type: 'folder',
                path: `/ScaleSupport/Accounts/${acc.accountId}/Visit_Proof`,
                fileCount: accPhotos.length,
                createdAt: acc.allocationDate,
                children: [],
              },
              {
                id: `drv_${acc.accountId}_voice_notes`,
                name: 'Voice_Notes',
                type: 'folder',
                path: `/ScaleSupport/Accounts/${acc.accountId}/Voice_Notes`,
                fileCount: accVoice.length,
                createdAt: acc.allocationDate,
                children: accVoice.map((v) => ({
                  id: v.driveFileId,
                  name: `${v.voiceNoteId}_Statement_${v.durationSeconds}s.mp3`,
                  type: 'file',
                  path: `/ScaleSupport/Accounts/${acc.accountId}/Voice_Notes/${v.voiceNoteId}.mp3`,
                  driveFileId: v.driveFileId,
                  size: `${Math.round(v.durationSeconds * 16)} KB`,
                  mimeType: 'audio/mpeg',
                  createdAt: v.date,
                })),
              },
            ],
          };
        }),
      },
      {
        id: 'drv_reports',
        name: 'Reports',
        type: 'folder',
        path: '/ScaleSupport/Reports',
        fileCount: 4,
        createdAt: '2026-08-01',
        children: [
          {
            id: 'drv_rep_monthly_aug',
            name: 'ScaleSupport_Monthly_Recovery_Report_August_2026.xlsx',
            type: 'file',
            path: '/ScaleSupport/Reports/ScaleSupport_Monthly_Recovery_Report_August_2026.xlsx',
            driveFileId: 'DRV_REP_MTH_AUG_2026',
            size: '1.2 MB',
            mimeType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
            createdAt: '2026-08-23',
          },
          {
            id: 'drv_rep_commission_10pct',
            name: 'Agent_10_Percent_Commission_Statement.csv',
            type: 'file',
            path: '/ScaleSupport/Reports/Agent_10_Percent_Commission_Statement.csv',
            driveFileId: 'DRV_REP_COM_10PCT',
            size: '84 KB',
            mimeType: 'text/csv',
            createdAt: '2026-08-23',
          },
        ],
      },
      {
        id: 'drv_system_files',
        name: 'System_Files',
        type: 'folder',
        path: '/ScaleSupport/System_Files',
        fileCount: 2,
        createdAt: '2026-08-01',
        children: [
          {
            id: 'drv_sys_schema',
            name: 'ScaleSupport_Database_19_Sheets_Schema.json',
            type: 'file',
            path: '/ScaleSupport/System_Files/ScaleSupport_Database_19_Sheets_Schema.json',
            driveFileId: 'DRV_SYS_SCHEMA_JSON',
            size: '42 KB',
            mimeType: 'application/json',
            createdAt: '2026-08-01',
          },
        ],
      },
    ],
  };
}

export function downloadSheetAsCSV(sheet: GoogleSheetTab) {
  const headers = sheet.columns.join(',');
  const rows = sheet.records.map((r) =>
    sheet.columns
      .map((col) => {
        const val = r[col] !== undefined ? String(r[col]) : '';
        if (val.includes(',') || val.includes('"') || val.includes('\n')) {
          return `"${val.replace(/"/g, '""')}"`;
        }
        return val;
      })
      .join(',')
  );

  const csvContent = [headers, ...rows].join('\n');
  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.setAttribute('href', url);
  link.setAttribute('download', `ScaleSupport_${sheet.sheetNumber}_${sheet.title.replace(/\s+/g, '_')}_${new Date().toISOString().slice(0, 10)}.csv`);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
}
